// frontend/src/pages/admin/ActorsPage.tsx
import { useEffect, useState } from "react";
import { Actor, apiClient, Role } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";

export function ActorsPage() {
  const { token } = useAuth();
  const [actors, setActors] = useState<Actor[]>([]);
  const [roles, setRoles] = useState<Role[]>([]);

  // Create form state
  const [displayName, setDisplayName] = useState("");
  const [ratingLevel, setRatingLevel] = useState<"high" | "normal" | "low" | "suspended">("normal");
  const [maxConsecutive, setMaxConsecutive] = useState(3);
  const [monthlyCap, setMonthlyCap] = useState<number | null>(null);
  const [notes, setNotes] = useState("");
  const [error, setError] = useState<string | null>(null);

  const refreshData = () => {
    if (!token) return;
    apiClient.getActors(token).then(setActors).catch((err) => setError(err.message));
    apiClient.getRoles(token).then(setRoles).catch((err) => setError(err.message));
  };

  useEffect(() => {
    refreshData();
  }, [token]);

  const handleCreateActor = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token) return;
    setError(null);
    try {
      await apiClient.createActor(token, {
        display_name: displayName,
        rating_level: ratingLevel,
        max_consecutive_performances: maxConsecutive,
        low_rating_monthly_cap: monthlyCap,
        notes: notes || null,
      });
      setDisplayName("");
      setRatingLevel("normal");
      setMaxConsecutive(3);
      setMonthlyCap(null);
      setNotes("");
      refreshData();
    } catch (err: any) {
      setError(err.message || "创建演员失败");
    }
  };

  return (
    <section>
      <h2>演员管理</h2>
      {error && <p role="alert" style={{ color: "red" }}>{error}</p>}

      <div className="panel" style={{ marginBottom: "20px" }}>
        <h3>新增演员</h3>
        <form onSubmit={handleCreateActor} style={{ display: "grid", gap: "10px", maxWidth: "400px" }}>
          <label>
            演员姓名
            <input aria-label="演员姓名" value={displayName} onChange={(e) => setDisplayName(e.target.value)} required />
          </label>
          <label>
            演员评级
            <select aria-label="演员评级" value={ratingLevel} onChange={(e) => setRatingLevel(e.target.value as any)}>
              <option value="high">高</option>
              <option value="normal">普通</option>
              <option value="low">低</option>
              <option value="suspended">暂停</option>
            </select>
          </label>
          <label>
            最大连场
            <input aria-label="最大连场" type="number" min={1} max={3} value={maxConsecutive} onChange={(e) => setMaxConsecutive(Number(e.target.value))} required />
          </label>
          <label>
            低评级上限
            <input type="number" min={0} value={monthlyCap ?? ""} onChange={(e) => setMonthlyCap(e.target.value ? Number(e.target.value) : null)} />
          </label>
          <label>
            备注
            <input value={notes} onChange={(e) => setNotes(e.target.value)} />
          </label>
          <button type="submit" className="button">保存演员</button>
        </form>
      </div>

      <div className="panel">
        <h3>演员列表</h3>
        <div style={{ display: "grid", gap: "20px" }}>
          {actors.map((actor) => (
            <ActorEditor
              key={actor.id}
              actor={actor}
              roles={roles}
              token={token || ""}
              onRefresh={refreshData}
              onError={setError}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

function ActorEditor({
  actor,
  roles,
  token,
  onRefresh,
  onError,
}: {
  actor: Actor;
  roles: Role[];
  token: string;
  onRefresh: () => void;
  onError: (msg: string | null) => void;
}) {
  const [maxConsecutive, setMaxConsecutive] = useState(actor.max_consecutive_performances);
  const [ratingLevel, setRatingLevel] = useState(actor.rating_level);
  const [monthlyCap, setMonthlyCap] = useState(actor.low_rating_monthly_cap);
  const [notes, setNotes] = useState(actor.notes || "");
  const [selectedRoleIds, setSelectedRoleIds] = useState<number[]>(actor.role_ids || []);

  const handleToggleRole = (roleId: number) => {
    setSelectedRoleIds((prev) =>
      prev.includes(roleId) ? prev.filter((id) => id !== roleId) : [...prev, roleId]
    );
  };

  const handleSave = async () => {
    onError(null);
    try {
      await apiClient.updateActor(token, actor.id, {
        max_consecutive_performances: maxConsecutive,
        rating_level: ratingLevel,
        low_rating_monthly_cap: monthlyCap,
        notes: notes || null,
      });
      await apiClient.replaceActorCapabilities(token, actor.id, selectedRoleIds);
      onRefresh();
    } catch (err: any) {
      onError(err.message || "更新演员失败");
    }
  };

  return (
    <div style={{ border: "1px solid #ccc", padding: "10px", borderRadius: "5px" }}>
      <h4>{actor.display_name}</h4>
      <div style={{ display: "grid", gap: "10px", gridTemplateColumns: "1fr 1fr", marginBottom: "10px" }}>
        <label>
          修改最大连场
          <input
            aria-label="修改最大连场"
            type="number"
            min={1}
            max={3}
            value={maxConsecutive}
            onChange={(e) => setMaxConsecutive(Number(e.target.value))}
          />
        </label>
        <label>
          评级
          <select value={ratingLevel} onChange={(e) => setRatingLevel(e.target.value as any)}>
            <option value="high">高</option>
            <option value="normal">普通</option>
            <option value="low">低</option>
            <option value="suspended">暂停</option>
          </select>
        </label>
        <label>
          低评级上限
          <input
            type="number"
            min={0}
            value={monthlyCap ?? ""}
            onChange={(e) => setMonthlyCap(e.target.value ? Number(e.target.value) : null)}
          />
        </label>
        <label>
          备注
          <input value={notes} onChange={(e) => setNotes(e.target.value)} />
        </label>
      </div>
      <div style={{ marginBottom: "10px" }}>
        <h5>可出演角色：</h5>
        <div style={{ display: "flex", gap: "10px", flexWrap: "wrap" }}>
          {roles.map((role) => (
            <label key={role.id}>
              <input
                type="checkbox"
                aria-label={role.name}
                checked={selectedRoleIds.includes(role.id)}
                onChange={() => handleToggleRole(role.id)}
              />
              {role.name}
            </label>
          ))}
        </div>
      </div>
      <button type="button" className="button" onClick={handleSave}>
        保存演员设置
      </button>
    </div>
  );
}

// frontend/src/pages/admin/ActorsPage.vue
<template>
  <section style="max-width: 1200px; margin: 0 auto;">
    <PageHeader title="演员管理" description="在此新增并管理在册演员的基础排班偏好、评级以及角色出演能力。" />

    <div v-if="error" style="padding: 12px; background: #ffeef0; color: #d9383a; border-radius: 6px; margin-bottom: 20px;" role="alert">
      {{ error }}
    </div>

    <div style="display: grid; grid-template-columns: 1fr 2fr; gap: 30px; align-items: start;">
      
      <!-- Left Column: Add Actor Form -->
      <div class="panel" style="margin: 0;">
        <h3>新增演员</h3>
        <form @submit.prevent="handleCreateActor" style="display: grid; gap: 16px; margin-top: 10px;">
          <div style="display: flex; flex-direction: column; gap: 6px;">
            <label for="actor-name-input">演员姓名</label>
            <input
              id="actor-name-input"
              aria-label="演员姓名"
              v-model="displayName"
              placeholder="例如：小展"
              required
              style="padding: 8px 12px; border-radius: 6px; background: rgba(255, 255, 255, 0.05); border: 1px solid var(--panel-border); color: var(--text-primary);"
            />
          </div>

          <div style="display: flex; flex-direction: column; gap: 6px;">
            <label for="actor-rating-select">演员评级</label>
            <select
              id="actor-rating-select"
              aria-label="演员评级"
              v-model="ratingLevel"
              style="padding: 8px 12px; border-radius: 6px; background: rgba(0, 0, 0, 0.8); border: 1px solid var(--panel-border); color: var(--text-primary);"
            >
              <option value="high">高</option>
              <option value="normal">普通</option>
              <option value="low">低</option>
              <option value="suspended">暂停</option>
            </select>
          </div>

          <div style="display: flex; flex-direction: column; gap: 6px;">
            <label for="actor-consecutive-input">最大连场</label>
            <input
              id="actor-consecutive-input"
              aria-label="最大连场"
              type="number"
              min="1"
              max="3"
              v-model.number="maxConsecutive"
              required
              style="padding: 8px 12px; border-radius: 6px; background: rgba(255, 255, 255, 0.05); border: 1px solid var(--panel-border); color: var(--text-primary);"
            />
          </div>

          <div style="display: flex; flex-direction: column; gap: 6px;">
            <label for="actor-monthly-cap-input">低评级上限</label>
            <input
              id="actor-monthly-cap-input"
              type="number"
              min="0"
              v-model.number="monthlyCap"
              style="padding: 8px 12px; border-radius: 6px; background: rgba(255, 255, 255, 0.05); border: 1px solid var(--panel-border); color: var(--text-primary);"
            />
          </div>

          <div style="display: flex; flex-direction: column; gap: 6px;">
            <label for="actor-notes-input">备注</label>
            <input
              id="actor-notes-input"
              v-model="notes"
              style="padding: 8px 12px; border-radius: 6px; background: rgba(255, 255, 255, 0.05); border: 1px solid var(--panel-border); color: var(--text-primary);"
            />
          </div>

          <button type="submit" style="margin-top: 8px; padding: 10px; border-radius: 6px; background: var(--primary); color: #fff; border: none; font-weight: 600; cursor: pointer;">保存演员</button>
        </form>
      </div>

      <!-- Right Column: Actors List -->
      <div class="panel" style="margin: 0;">
        <h3>演员列表 ({{ actors.length }})</h3>
        <p v-if="actors.length === 0" style="color: var(--text-secondary); margin-top: 10px;">暂无演员记录。</p>
        <div v-else style="display: grid; gap: 20px; margin-top: 16px;">
          <ActorEditor
            v-for="actor in actors"
            :key="actor.id"
            :actor="actor"
            :roles="roles"
            :token="authStore.token || ''"
            @refresh="refreshData"
            @error="setError"
          />
        </div>
      </div>

    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useAuthStore } from "../../auth/store";
import { adminApi, Actor, Role } from "../../api/admin";
import PageHeader from "../../components/PageHeader.vue";
import ActorEditor from "../../components/admin/ActorEditor.vue";

const authStore = useAuthStore();

const actors = ref<Actor[]>([]);
const roles = ref<Role[]>([]);

const displayName = ref("");
const ratingLevel = ref<"high" | "normal" | "low" | "suspended">("normal");
const maxConsecutive = ref(3);
const monthlyCap = ref<number | null>(null);
const notes = ref("");
const error = ref<string | null>(null);

const setError = (msg: string | null) => {
  error.value = msg;
};

const refreshData = () => {
  if (!authStore.token) return;
  adminApi.getActors(authStore.token).then((res) => actors.value = res).catch((err) => error.value = err.message);
  adminApi.getRoles(authStore.token).then((res) => roles.value = res).catch((err) => error.value = err.message);
};

onMounted(() => {
  refreshData();
});

const handleCreateActor = async () => {
  if (!authStore.token) return;
  error.value = null;
  try {
    await adminApi.createActor(authStore.token, {
      display_name: displayName.value,
      rating_level: ratingLevel.value,
      max_consecutive_performances: maxConsecutive.value,
      low_rating_monthly_cap: monthlyCap.value || null,
      notes: notes.value || null,
    });
    displayName.value = "";
    ratingLevel.value = "normal";
    maxConsecutive.value = 3;
    monthlyCap.value = null;
    notes.value = "";
    refreshData();
  } catch (err: any) {
    error.value = err.message || "创建演员失败";
  }
};
</script>
